// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTestCat = "test_cat"

// TestCat mapped from table <test_cat>
type TestCat struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CatName   string    `gorm:"column:cat_name" json:"catName"` // 名称
	CreatedBy string    `gorm:"column:created_by" json:"createdBy"`
	CreatedAt time.Time `gorm:"column:created_at" json:"createdAt"`
	UpdatedBy string    `gorm:"column:updated_by" json:"updatedBy"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updatedAt"`
}

// TableName TestCat's table name
func (*TestCat) TableName() string {
	return TableNameTestCat
}
