mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: passwd
  database: ai_iotman
  conn: charset=utf8mb4&parseTime=True
gen:
  dmlFolder: ./db_dml
  genRuoyiVue3:
    enable: true
    projectRoot: ./example/ruoyi_vue3
  genVueElementAdmin:
    enable: true
    projectRoot: ./example/vue_element_admin
  genApi: 
    enable: true
    overWrite: true
    apiGroup: v1
    excludeColumnsForQueryParameters:
      - deleted
      - lastmodified
    excludeColumnsForResponse:
      - deleted
  genBiz: 
    enable: true
    overWrite: true
  genDataSource: 
    enable: true
    overWrite: false
  genDal: 
    enable: true
    overWrite: true
  dataSources:
    - dataSourceName: db1
      dsn: root:passwd@(127.0.0.1:3306)/ai_iotman?charset=utf8mb4&parseTime=True
      # code: app.AlertDB
  genTables:
    - tableName: sys_role
      parentMenu: 生成代码
    - tableName: test_cat
      parentMenu: 生成代码
  outputRoot: ./example
  packageRoot: github.com/okgotool/gocodegen/example
